'use strict';
import * as prettier from 'prettier';
import ts from 'typescript';

import { FileTypeInformation, ModuleClassDeclaration } from './typeInformation';

const prefix = `Automatically generated by expo-cli.

This autogenerated file provides TS types for native Expo module or view,
and works out of the box with local native modules.
`;

function getPrefix() {
  return [ts.factory.createJSDocComment(prefix)];
}

const newlineIdentifier = ts.factory.createIdentifier('\n\n') as any;

function getOneNamedImport(importedName: string, importFromName: string) {
  return ts.factory.createImportDeclaration(
    undefined,
    ts.factory.createImportClause(
      undefined,
      undefined,
      ts.factory.createNamedImports([
        ts.factory.createImportSpecifier(
          false,
          undefined,
          ts.factory.createIdentifier(importedName)
        ),
      ])
    ),
    ts.factory.createStringLiteral(importFromName),
    undefined
  );
}

function getExportedModuleDeclaration(moduleClassDeclaration: ModuleClassDeclaration): ts.Node[] {
  return [
    ts.factory.createClassDeclaration(
      [ts.factory.createModifier(ts.SyntaxKind.ExportKeyword)],
      moduleClassDeclaration.name + 'GenericNameEnding',
      undefined,
      [
        ts.factory.createHeritageClause(ts.SyntaxKind.ExtendsKeyword, [
          ts.factory.createExpressionWithTypeArguments(
            ts.factory.createIdentifier('NativeModule'),
            undefined
          ),
        ]),
      ],
      ([] as ts.ClassElement[]).concat(
        moduleClassDeclaration.constants.map((cd) =>
          ts.factory.createPropertyDeclaration(
            undefined,
            cd.name,
            undefined,
            ts.factory.createTypeReferenceNode(cd.typename, []),
            undefined
          )
        ),
        moduleClassDeclaration.functions.map((fd) =>
          ts.factory.createMethodDeclaration(
            [],
            undefined,
            fd.name,
            undefined,
            undefined,
            ([] as ts.ParameterDeclaration[]).concat(
              fd.arguments.map((ad) =>
                ts.factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  ad.name,
                  undefined,
                  ts.factory.createTypeReferenceNode(ad.typename.toString()),
                  undefined
                )
              )
            ),
            ts.factory.createTypeReferenceNode(fd.returnType.toString()),
            undefined
          )
        )
      )
    ),
  ];
}

function getModuleTypesDeclarationsForModule(
  moduleClassDeclaration: ModuleClassDeclaration
): ts.Node[] {
  return ([] as ts.Node[]).concat(
    getPrefix(),
    newlineIdentifier,
    getOneNamedImport('NativeModule', 'expo'),
    newlineIdentifier,
    getExportedModuleDeclaration(moduleClassDeclaration)
  );
}

async function prettifyCode(text: string, parser: 'babel' | 'typescript' = 'babel') {
  return await prettier.format(text, {
    parser,
    tabWidth: 2,
    printWidth: 100,
    trailingComma: 'none',
    singleQuote: true,
  });
}

async function prettyPrintTSToString(file: string, elements: ts.Node[]) {
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const resultFile = ts.createSourceFile(
    file,
    '',
    ts.ScriptTarget.Latest,
    false,
    ts.ScriptKind.TSX
  );
  const viewTypes = ts.factory.createNodeArray(elements);
  const printedTs = printer.printList(
    ts.ListFormat.MultiLine + ts.ListFormat.PreserveLines,
    viewTypes,
    resultFile
  );
  return await prettifyCode(printedTs, 'typescript');
}

export async function getGeneratedViewTypesFileContent(
  file: string,
  FileTypeInformation: FileTypeInformation
): Promise<string> {
  const outputModuleDefinition = FileTypeInformation.moduleClasses[0];
  return prettyPrintTSToString(file, getModuleTypesDeclarationsForModule(outputModuleDefinition));
}

export async function getGeneratedModuleTypesFileContent(
  file: string,
  FileTypeInformation: FileTypeInformation
): Promise<string> {
  const outputModuleDefinition = FileTypeInformation.moduleClasses[0];
  return prettyPrintTSToString(file, getModuleTypesDeclarationsForModule(outputModuleDefinition));
}
