'use strict';
import ts from 'typescript';

import {
  BasicType,
  ClassDeclaration,
  FileTypeInformation,
  FunctionDeclaration,
  ModuleClassDeclaration,
  Type,
  TypeKind,
} from './typeInformation';

const prefix = `Automatically generated by expo-cli.

This autogenerated file provides TS types for native Expo module or view,
and works out of the box with local native modules.
`;

function getPrefix() {
  return [ts.factory.createJSDocComment(prefix)];
}

const newlineIdentifier = ts.factory.createIdentifier('\n\n') as any;

function getOneNamedImport(importedName: string, importFromName: string) {
  return ts.factory.createImportDeclaration(
    undefined,
    ts.factory.createImportClause(
      undefined,
      undefined,
      ts.factory.createNamedImports([
        ts.factory.createImportSpecifier(
          false,
          undefined,
          ts.factory.createIdentifier(importedName)
        ),
      ])
    ),
    ts.factory.createStringLiteral(importFromName),
    undefined
  );
}

function getExportedModuleDeclaration(moduleClassDeclaration: ModuleClassDeclaration): ts.Node[] {
  return [
    ts.factory.createClassDeclaration(
      [ts.factory.createModifier(ts.SyntaxKind.ExportKeyword)],
      moduleClassDeclaration.name + 'GenericNameEnding',
      undefined,
      [
        ts.factory.createHeritageClause(ts.SyntaxKind.ExtendsKeyword, [
          ts.factory.createExpressionWithTypeArguments(
            ts.factory.createIdentifier('NativeModule'),
            undefined
          ),
        ]),
      ],
      ([] as ts.ClassElement[]).concat(
        moduleClassDeclaration.constants.map((cd) =>
          ts.factory.createPropertyDeclaration(
            undefined,
            cd.name,
            undefined,
            ts.factory.createTypeReferenceNode(cd.typename, []),
            undefined
          )
        ),
        moduleClassDeclaration.functions.map((fd) =>
          ts.factory.createMethodDeclaration(
            [],
            undefined,
            fd.name,
            undefined,
            undefined,
            ([] as ts.ParameterDeclaration[]).concat(
              fd.arguments.map((ad) =>
                ts.factory.createParameterDeclaration(
                  undefined,
                  undefined,
                  ad.name,
                  undefined,
                  ts.factory.createTypeReferenceNode(ad.typename.toString()),
                  undefined
                )
              )
            ),
            ts.factory.createTypeReferenceNode(fd.returnType.toString()),
            undefined
          )
        )
      )
    ),
  ];
}

function getArgumentDeclaration(arg: { name: string; typename: Type }): ts.ParameterDeclaration {
  return ts.factory.createParameterDeclaration(
    undefined,
    undefined,
    arg.name,
    undefined,
    mapTypeToTsNode(arg.typename),
    undefined
  );
}

function getClassAsyncMethodDeclaration(
  functionDeclaration: FunctionDeclaration
): ts.MethodDeclaration {
  return getClassMethodDeclration(functionDeclaration, true);
}

function getClassSyncMethodDeclaration(
  functionDeclaration: FunctionDeclaration
): ts.MethodDeclaration {
  return getClassMethodDeclration(functionDeclaration, false);
}

function getClassMethodDeclration(
  functionDeclaration: FunctionDeclaration,
  async: boolean
): ts.MethodDeclaration {
  return ts.factory.createMethodDeclaration(
    // isAsync ? [ts.factory.createModifier(ts.SyntaxKind.AsyncKeyword)] : [],
    [],
    undefined,
    functionDeclaration.name,
    undefined,
    undefined,
    functionDeclaration.arguments.map(getArgumentDeclaration),
    ts.factory.createTypeReferenceNode(functionDeclaration.returnType.type.toString()),
    undefined
  );
}

function mapBasicTypeToTsNode(basicType: BasicType): ts.TypeNode {
  return ts.factory.createKeywordTypeNode(
    (() => {
      switch (basicType) {
        case BasicType.ANY:
          return ts.SyntaxKind.AnyKeyword;
        case BasicType.BOOLEAN:
          return ts.SyntaxKind.BooleanKeyword;
        case BasicType.NUMBER:
          return ts.SyntaxKind.NumberKeyword;
        case BasicType.STRING:
          return ts.SyntaxKind.StringKeyword;
        case BasicType.VOID:
          return ts.SyntaxKind.VoidKeyword;
      }
    })()
  );
}

function mapTypeToTsNode(type: Type): ts.TypeNode {
  switch (type.kind) {
    case TypeKind.BASIC:
      return mapBasicTypeToTsNode(type.type as BasicType);
    case TypeKind.IDENTIFIER:
      return ts.factory.createTypeReferenceNode(type.type as string);
  }
  return ts.factory.createTypeReferenceNode('any');
  //   return ts.SyntaxKind.AnyKeyword;
}

function getExportedClassDeclaration(classDeclaration: ClassDeclaration): ts.Node[] {
  return ([] as ts.Node[]).concat(
    ts.factory.createClassDeclaration(
      [ts.factory.createToken(ts.SyntaxKind.ExportKeyword)],
      ts.factory.createIdentifier(classDeclaration.name),
      undefined,
      undefined,
      ([] as ts.MethodDeclaration[]).concat(
        classDeclaration.methods.map(getClassSyncMethodDeclaration),
        classDeclaration.asyncMethods.map(getClassAsyncMethodDeclaration)
      )
    )
  );
}

function getModuleTypesDeclarationsForModule(
  moduleClassDeclaration: ModuleClassDeclaration
): ts.Node[] {
  return ([] as ts.Node[]).concat(
    getPrefix(),
    newlineIdentifier,
    getOneNamedImport('NativeModule', 'expo'),
    newlineIdentifier,
    moduleClassDeclaration.classes.flatMap(getExportedClassDeclaration),
    newlineIdentifier,
    getExportedModuleDeclaration(moduleClassDeclaration)
  );
}

async function prettifyCode(text: string, parser: 'babel' | 'typescript' = 'babel') {
  //   return await prettier.format(text, {
  //     parser,
  //     tabWidth: 2,
  //     printWidth: 100,
  //     trailingComma: 'none',
  //     singleQuote: true,
  //   });
  return text;
}

async function prettyPrintTSToString(file: string, elements: ts.Node[]) {
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const resultFile = ts.createSourceFile(
    file,
    '',
    ts.ScriptTarget.Latest,
    false,
    ts.ScriptKind.TSX
  );
  const viewTypes = ts.factory.createNodeArray(elements);
  const printedTs = printer.printList(
    ts.ListFormat.MultiLine + ts.ListFormat.PreserveLines,
    viewTypes,
    resultFile
  );
  return await prettifyCode(printedTs, 'typescript');
}

export async function getGeneratedViewTypesFileContent(
  file: string,
  FileTypeInformation: FileTypeInformation
): Promise<string> {
  const outputModuleDefinition = FileTypeInformation.moduleClasses[0];
  return prettyPrintTSToString(file, getModuleTypesDeclarationsForModule(outputModuleDefinition));
}

export async function getGeneratedModuleTypesFileContent(
  file: string,
  FileTypeInformation: FileTypeInformation
): Promise<string> {
  const outputModuleDefinition = FileTypeInformation.moduleClasses[0];
  return prettyPrintTSToString(file, getModuleTypesDeclarationsForModule(outputModuleDefinition));
}
