import { useEffect, useState } from 'react';
import { View } from 'react-native';

import HeadingText from '../components/HeadingText';
import MonoText from '../components/MonoText';
import { Page } from '../components/Page';
import { getGeneratedModuleTypesFileContent } from 'expo-type-information';
// import * from 'expo-type-information'

const swiftModuleExample0 = `import ExpoModulesCore
import WebKit

public class TestModule: Module {
  public func definition() -> ModuleDefinition {
    Constant("StringConstant") { () -> Int in
      return "Swift constant 1283"
    }
  }
}
`;

export default function TypeInformationScreen() {
  const [generatedDTS, setGeneratedDTS] = useState<string>(`/**
 * Automatically generated by expo-type-information.
 *
 * This autogenerated file provides TS types for native Expo module or view,
 * and works out of the box with inline native modules.
 *  */

import { NativeModule } from 'expo';

export declare class TestModule extends NativeModule {
  readonly StringConstant: number;
}

const _default: TestModule;
export default _default;`);

  useEffect(() => {
    getGeneratedModuleTypesFileContent().then(setGeneratedDTS());
  }, []);

  return (
    <Page>
      <View>
        <HeadingText>Module types generation</HeadingText>
      </View>
      <View>
        <HeadingText>Examples:</HeadingText>
        <View>
          <HeadingText>Swift module:</HeadingText>
          <MonoText>{swiftModuleExample0}</MonoText>
          <HeadingText>Generated d.ts file:</HeadingText>
          <MonoText>{generatedDTS}</MonoText>
        </View>
      </View>
    </Page>
  );
}
